name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details below.

  - type: dropdown
    id: subdomain
    attributes:
      label: Target Subdomain
      description: Where should this feature be added?
      options:
        - Guitar Platform (guitar.projectlavos.com)
        - Main Site (projectlavos.com)
        - Demos (demos.projectlavos.com)
        - About (about.projectlavos.com)
        - Services (services.projectlavos.com)
        - Backend/API
        - Infrastructure
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Add a button that allows users to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you thought about?
      placeholder: I considered X, but Y would be better because...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (blocks major functionality)
        - High (significantly improves UX)
        - Medium (nice to have)
        - Low (minor enhancement)
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: Who would benefit from this feature?
      options:
        - Guitar learners (students)
        - All users
        - Developers/maintainers
        - Business users
        - Mobile users
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Add mockups, wireframes, or links to similar features
      placeholder: Drag and drop images or paste links here

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical details or constraints to consider?
      placeholder: This might require changes to the database schema...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
